package org.viodo.toshell.ui.form;

import lombok.Getter;

import javax.swing.*;
import java.awt.*;

/**
 * 主界面
 *
 * @author chenxc
 */
@Getter
public class MainForm {

    private JPanel mainPanel;
    private JSplitPane lrSplitPane;

    private static MainForm instance;

    public MainForm() {

    }

    public static MainForm getInstance() {
        if (instance == null) {
            instance = new MainForm();
        }
        return instance;
    }

    public void initComponents() {
        instance.getMainPanel().updateUI();
        instance.getMainPanel().add(StatusBar.getInstance(), BorderLayout.SOUTH);
        instance.getLrSplitPane().setRightComponent(SessionForm.getInstance().getMainPanel());
        instance.getLrSplitPane().setLeftComponent(SessionManager.getInstance().getMainPanel());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setForeground(new Color(-12828863));
        lrSplitPane = new JSplitPane();
        lrSplitPane.setDividerLocation(0);
        lrSplitPane.setDividerSize(5);
        lrSplitPane.setForeground(new Color(-12828863));
        mainPanel.add(lrSplitPane, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
