package org.viodo.toshell.ui.form;

import lombok.Getter;

import javax.swing.*;
import java.awt.*;

/**
 * 主界面
 *
 * @author chenxc
 */
@Getter
public class MainForm {

    private JPanel mainPanel;

    private JSplitPane lrSplitPane;

    private JSplitPane tbSplitPane;

    private static MainForm instance;

    public MainForm() {

    }

    public static MainForm getInstance() {
        if (instance == null) {
            instance = new MainForm();
        }
        return instance;
    }

    public void initComponents() {
        instance.getMainPanel().updateUI();
        instance.getMainPanel().add(StatusBar.getInstance(), BorderLayout.SOUTH);
        instance.getLrSplitPane().setRightComponent(MonitorForm.getInstance().getMainPanel());
        instance.getTbSplitPane().setTopComponent(SessionForm.getInstance().getMainPanel());
        instance.getTbSplitPane().setBottomComponent(SftpForm.getInstance().getMainPanel());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        lrSplitPane = new JSplitPane();
        lrSplitPane.setDividerLocation(500);
        lrSplitPane.setDividerSize(2);
        lrSplitPane.setEnabled(true);
        mainPanel.add(lrSplitPane, BorderLayout.CENTER);
        tbSplitPane = new JSplitPane();
        tbSplitPane.setDividerLocation(200);
        tbSplitPane.setDividerSize(2);
        tbSplitPane.setEnabled(true);
        tbSplitPane.setOrientation(0);
        tbSplitPane.setToolTipText("");
        lrSplitPane.setLeftComponent(tbSplitPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
