package org.viodo.toshell.ui.form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;

/**
 * 主界面
 *
 * @author chenxc
 */
@Getter
public class MainForm {

    private JPanel mainPanel;

    private JSplitPane lrSplitPane;

    private JSplitPane tbSplitPane;

    private static MainForm instance;

    public MainForm() {

    }

    public static MainForm getInstance() {
        if (instance == null) {
            instance = new MainForm();
        }
        return instance;
    }

    public void initComponents() {
        instance.getMainPanel().updateUI();
        instance.getLrSplitPane().setRightComponent(MonitorPanel.getInstance().getMainPanel());
        instance.getTbSplitPane().setTopComponent(SessionForm.getInstance().getMainPanel());
        instance.getTbSplitPane().setBottomComponent(SftpForm.getInstance().getMainPanel());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        lrSplitPane = new JSplitPane();
        lrSplitPane.setDividerLocation(500);
        lrSplitPane.setDividerSize(1);
        lrSplitPane.setEnabled(true);
        mainPanel.add(lrSplitPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        tbSplitPane = new JSplitPane();
        tbSplitPane.setDividerLocation(200);
        tbSplitPane.setDividerSize(1);
        tbSplitPane.setEnabled(true);
        tbSplitPane.setOrientation(0);
        tbSplitPane.setToolTipText("");
        lrSplitPane.setLeftComponent(tbSplitPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
