package org.viodo.toshell.ui.form;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.Getter;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.util.function.BiConsumer;

import static com.formdev.flatlaf.FlatClientProperties.*;

/**
 * session form
 *
 * @author chenxc
 */
@Getter
public class SessionForm {
    private JPanel mainPanel;
    private JTabbedPane sessionTab;

    private static SessionForm instance;

    public static SessionForm getInstance() {
        if (instance == null) {
            instance = new SessionForm();
        }
        return instance;
    }

    public SessionForm() {
        initTab();
    }

    private void initTab() {
        JToolBar leading = new JToolBar();
        leading.setFloatable(false);
        leading.setBorder(null);
        leading.add(new JButton(new FlatSVGIcon("icons/project.svg")));

        JToolBar trailing = new JToolBar();
        trailing.setFloatable(false);
        trailing.setBorder(null);
        trailing.add(new JButton(new FlatSVGIcon("icons/add.svg")));

        sessionTab.putClientProperty(TABBED_PANE_TAB_CLOSABLE, true);
        sessionTab.putClientProperty(TABBED_PANE_TAB_CLOSE_TOOLTIPTEXT, "Close");
        sessionTab.putClientProperty(TABBED_PANE_TAB_CLOSE_CALLBACK,
                (BiConsumer<JTabbedPane, Integer>) (tabPane, tabIndex) -> {
                    AWTEvent e = EventQueue.getCurrentEvent();
                    int modifiers = (e instanceof MouseEvent) ? ((MouseEvent) e).getModifiers() : 0;
                    JOptionPane.showMessageDialog(this.$$$getRootComponent$$$(), "Closed tab '" + tabPane.getTitleAt(tabIndex) + "'."
                                    + "\n\n(modifiers: " + MouseEvent.getMouseModifiersText(modifiers) + ")",
                            "Tab Closed", JOptionPane.PLAIN_MESSAGE);
                });

        sessionTab.putClientProperty(TABBED_PANE_TRAILING_COMPONENT, trailing);

        sessionTab.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-1));
        sessionTab = new JTabbedPane();
        mainPanel.add(sessionTab, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setEnabled(true);
        sessionTab.addTab("Untitled", panel1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
